[package]
name = "bhvextractor"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
inflate = "0.4.5"
serde = { version = "1.0.217", features = ["serde_derive"] }
serde_json = "1.0.134"
